# Generated by Django 5.0.7 on 2024-07-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geometry", models.IntegerField(default=0)),
                ("properties", models.CharField(max_length=200)),
            ],
        ),
    ]
