# Generated by Django 5.0.7 on 2024-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geojson", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="properties",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="geometry",
        ),
        migrations.AddField(
            model_name="feature",
            name="geom_text",
            field=models.CharField(default=int, max_length=3000),
            preserve_default=False,
        ),
    ]
