# Generated by Django 5.0.7 on 2024-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geojson", "0002_rename_properties_feature_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="geom_text",
            field=models.TextField(max_length=3000),
        ),
    ]
