# Generated by Django 5.0.7 on 2024-07-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geojson", "0003_alter_feature_geom_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feature",
            new_name="municipalities_nl",
        ),
        migrations.AlterModelTable(
            name="municipalities_nl",
            table="municipalities_nl",
        ),
    ]
