# Generated by Django 5.0.7 on 2024-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geojson", "0004_rename_feature_municipalities_nl_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MunicipalitiesNl",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("geom_text", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "municipalities_nl",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="municipalities_nl",
        ),
    ]
