# Generated by Django 5.0.7 on 2024-07-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geojson", "0005_municipalitiesnl_delete_municipalities_nl"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipalitiesnl",
            options={"managed": False, "ordering": ["ogc_fid"]},
        ),
    ]
